# Generated by Django 5.0.3 on 2024-03-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='petSims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=120)),
                ('petBreed', models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('pink', 'PINK')], default='pink', max_length=6)),
            ],
        ),
    ]
