# Generated by Django 5.0.3 on 2024-04-06 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charisma_mod', models.FloatField(default=1)),
                ('charisma_boost', models.IntegerField(default=0)),
                ('strength_mod', models.FloatField(default=1)),
                ('strength_boost', models.IntegerField(default=0)),
                ('dexterity_mod', models.FloatField(default=1)),
                ('dexterity_boost', models.IntegerField(default=0)),
                ('intelligence_mod', models.FloatField(default=1)),
                ('intelligence_boost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='petBreed',
            fields=[
                ('breedName', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('progress_needed', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('skillset', models.CharField(max_length=100)),
                ('stat1', models.CharField(max_length=100)),
                ('stat2', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=120)),
                ('stress', models.IntegerField()),
                ('xp', models.IntegerField(default=0)),
                ('next_xp', models.IntegerField(default=128)),
                ('level', models.IntegerField(default=1)),
                ('stress_limit', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('strength_growth', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('dexterity_growth', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('intelligence_growth', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('charisma_growth', models.IntegerField()),
                ('petBreed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetSim.petbreed')),
            ],
        ),
        migrations.CreateModel(
            name='userPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=120, unique=True)),
                ('petBreed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PetSim.petbreed')),
                ('userInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_pet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
