# Generated by Django 5.0.3 on 2024-03-29 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='petBreed',
            fields=[
                ('breedName', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='userPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=120)),
                ('petBreed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetSim.petbreed')),
                ('userInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_pet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
