# Generated by Django 5.0.3 on 2024-03-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetSim', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='petSims',
            new_name='petSim',
        ),
    ]
