# Generated by Django 5.0.3 on 2024-04-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSim', '0002_task_name_alter_task_skillset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='stat1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='stat2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
