# Generated by Django 5.0.3 on 2024-05-31 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetSim', '0002_alter_userpet_petbreed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charisma_mod', models.FloatField(default=1)),
                ('charisma_boost', models.IntegerField(default=0)),
                ('strength_mod', models.FloatField(default=1)),
                ('strength_boost', models.IntegerField(default=0)),
                ('dexterity_mod', models.FloatField(default=1)),
                ('dexterity_boost', models.IntegerField(default=0)),
                ('intelligence_mod', models.FloatField(default=1)),
                ('intelligence_boost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=120)),
                ('stress', models.IntegerField()),
                ('xp', models.IntegerField(default=0)),
                ('next_xp', models.IntegerField(default=128)),
                ('level', models.IntegerField(default=1)),
                ('stress_limit', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('strength_growth', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('dexterity_growth', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('intelligence_growth', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('charisma_growth', models.IntegerField()),
                ('petBreed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetSim.petbreed')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('progress', models.IntegerField()),
                ('progress_needed', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('stat1', models.CharField(blank=True, max_length=100, null=True)),
                ('stat2', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
                ('skillset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetSim.petbreed')),
            ],
        ),
    ]
